"""create forklift_data table

Revision ID: 118d820d80d6
Revises: 
Create Date: 2023-10-21 10:23:17.905858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118d820d80d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forklift_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('forklift', sa.Integer(), nullable=True),
    sa.Column('warehouse', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('point', sa.String(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forklift_data_forklift'), 'forklift_data', ['forklift'], unique=False)
    op.create_index(op.f('ix_forklift_data_id'), 'forklift_data', ['id'], unique=False)
    op.create_index(op.f('ix_forklift_data_order'), 'forklift_data', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forklift_data_order'), table_name='forklift_data')
    op.drop_index(op.f('ix_forklift_data_id'), table_name='forklift_data')
    op.drop_index(op.f('ix_forklift_data_forklift'), table_name='forklift_data')
    op.drop_table('forklift_data')
    # ### end Alembic commands ###
